### ISSUE TITLE
pip install PyMsgBox error

### ISSUE THREAD

**Issue by afishpro** [asweigart/PyMsgBox#10]
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting PyMsgBox
  Using cached https://mirrors.aliyun.com/pypi/packages/7d/ff/4c6f31a4f08979f12a663f2aeb6c8b765d3bd592e66eaaac445f547bb875/PyMsgBox-1.0.9.tar.gz (18 kB)
  ERROR: Error expected str, bytes or os.PathLike object, not NoneType while executing command 'e:\code\fh_projects\venv\scripts\python.exe' 'e:\code\fh_projects\venv\lib\site-packages\pip' install --ignore-installed --no-user --pre
fix 'C:\Users\Administrator\AppData\Local\Temp\pip-build-env-s4gdldp2\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host https --trusted-host '' --tru
sted-host trusted-host --trusted-host '此参数是为了避免麻烦，否则使用的时候可能会提示不受信任' -- 'setuptools>=40.8.0' wheel
  Installing build dependencies ... error
ERROR: Exception:
Traceback (most recent call last):
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'pymsgbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
    status = self.run(options, args)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\commands\install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 82, in from_requirement
    if not cands:
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 38, in _iter_built
    candidate = func()
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 167, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 300, in __init__
    super().__init__(
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 311, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 457, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 500, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 66, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\distributions\sdist.py", line 39, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\distributions\sdist.py", line 67, in _setup_isolation
    self.req.build_env.install_requirements(
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\build_env.py", line 206, in install_requirements
    call_subprocess(args, spinner=spinner)
  File "e:\code\fh_projects\venv\lib\site-packages\pip\_internal\utils\subprocess.py", line 181, in call_subprocess
    proc = subprocess.Popen(
  File "D:\Dev\python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Dev\python\Python39\lib\subprocess.py", line 1356, in _execute_child
    args = list2cmdline(args)
  File "D:\Dev\python\Python39\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "D:\Dev\python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by afishpro** [comment]
system: windows 10
python: python3.9.1
IDE: pycharm

**Comment by afishpro** [comment]
pip install pymsgbox=1.0.7 not error

**Comment by yhabtemi-intel** [comment]
See the same thing on our pypi mirrors.  The setuptools >=40.8.0 pip thread does not care over our credentials.  --ignore-installed forces us to install setuptools despite meeting the requirement.
